name: sigmakuanta
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  go_router: ^14.2.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.2.0
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

